version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snowman-soup"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tujg7utm2u1n"
s3_prefix = "snowman-soup"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
