AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for snowmansoup, a basic Serverless API for CRUD soup functionality

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SnowmanSoupFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: flask_api/
      Handler: app.app
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref SnowmanSoupTable
          REGION_NAME: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SnowmanSoupTable
      Events:
        FetchSoups:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /soups
            Method: get
        CreateSoup:
          Type: Api
          Properties:
            Path: /soups
            Method: post

  SnowmanSoupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: snowman-soups
      AttributeDefinitions:
        - AttributeName: soupId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: soupId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SnowmanSoupApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/soups/"
  SnowmanSoupFunction:
    Description: "Melt the snowman"
    Value: !GetAtt SnowmanSoupFunction.Arn
  SnowmanSoupFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SnowmanSoupFunction.Arn
